###
#
# Custom workflow matrix configurations
#
# @link https://github.com/gocodebox/.github/tree/trunk/.github/actions/setup-matrix
#
###
Test PHPUnit:
  merge: append
  BEHAT_TAGS: ~@api-integration

  include:
    - name-append: (API Integration Tests)
      PHP: '8.0'
      WP: '5.8'
      BEHAT_TAGS: @api-integration
