import:
 - gocodebox/lifterlms:.config/travis/main.yml

jobs:
  fast_finish: true

  allow_failures:
  - env: WP_VERSION=nightly
  - env: WP_VERSION=latest RUN_CODE_COVERAGE=1
  - php: nightly

  exclude:
  # CLI doesn't support PHP 7.3
  - php: "7.3"
  # CLI only supports the last 2 major versions of WP core.
  - env: WP_VERSION="5.6"
  - env: WP_VERSION="5.5"
  - env: WP_VERSION="5.4"

before_install:
  # Disable xDebug for faster builds
  - |
    if [ "1" != $RUN_CODE_COVERAGE ] && [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  # Raise PHP memory limit to 2048MB
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Install composer deps.
  - composer install

install:
  - composer run tests-install

