###
#
# This workflow file is deployed into this repository via the "Sync Organization Files" workflow
#
# Direct edits to this file are at risk of being overwritten by the next sync. All edits should be made
# to the source file.
#
# @see Sync workflow {@link https://github.com/gocodebox/.github/actions/workflows/workflow-sync.yml}
# @see Workflow template {@link https://github.com/gocodebox/.github/blob/trunk/.github/workflows/issue-triage.yml}
#
###
name: New Issue Triage and Assignment

on:
  issues:
    types: [ opened ]

jobs:
  handle-new-issue:
    runs-on: ubuntu-latest
    env:
      PRIMARY_CODEOWNER: '@thomasplevy'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add to project.
      #################
      - name: Add to "Triage" project
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Triage
          column: Awaiting Triage
          repo-token: ${{ secrets.ORG_WORKFLOWS }}

      # Assign to the project's CODEOWNER.
      ####################################
      - name: Check CODEOWNERS file existence
        id: codeowners_file_exists
        uses: andstor/file-existence-action@v1
        with:
          files: .github/CODEOWNERS

      - name: Parse CODEOWNERS file
        id: codeowner
        if: steps.codeowners_file_exists.outputs.files_exists == 'true'
        uses: SvanBoxel/codeowners-action@v1
        with:
          path: .github/CODEOWNERS
      
      - name: Update PRIMARY_CODEOWNER env var
        if: steps.codeowners_file_exists.outputs.files_exists == 'true'
        run: |
          echo PRIMARY_CODEOWNER=$( echo '${{ steps.codeowner.outputs.codeowners }}' | jq -r '."*"[0]' ) >> $GITHUB_ENV   

      - name: Strip @ from username
        run: |
          echo "PRIMARY_CODEOWNER=${PRIMARY_CODEOWNER#?}" >> $GITHUB_ENV

      - name: Assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.ORG_WORKFLOWS }}
          assignees: ${{ env.PRIMARY_CODEOWNER }}