name: Move new issues into Triage

on:
  issues:
    types: [ opened ]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Triage
          column: Awaiting Triage
          repo-token: ${{ secrets.ORG_WORKFLOWS }}
