name: PHP Code Coverage Report

on:
  workflow_dispatch:
  pull_request:
  # Once daily at 00:00 UTC.
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true


jobs:

  check-secret:
    name: "Check for required secret"
    runs-on: ubuntu-latest
    outputs:
      has-secret: ${{ steps.check-secret.outputs.has-secret }}
    steps:
      - name: Test secret
        id: check-secret
        run: |
          if [ ! -z "${{ secrets.CC_TEST_REPORTER_ID }}" ]; then
            echo "::set-output name=has-secret::true"
          fi

  test:
    name: "PHP Test Coverage"
    runs-on: ubuntu-latest

    needs: check-secret

    if: ${{ 'true' == needs.check-secret.outputs.has-secret }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: gocodebox/.github/.github/actions/setup-phpunit@trunk
        with:
          php-version: "8.0"
          wp-version: "5.8"
          coverage: "xdebug"
          env-file: ".github/.env.php-test-coverage"
          secrets: ${{ toJSON( secrets ) }}

      - name: Run Tests
        run: composer run tests

      - name: Upload Test Coverage Reports
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/tmp/coverage/clover-behat/*.xml:clover
