name: PR Ready for Review

on:
  pull_request_target:
    types: [ ready_for_review, review_requested ]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Active
          column: Ready for Review
          repo-token: ${{ secrets.ORG_WORKFLOWS }}
